version: '3.9'
services:
  backend:
    image: sisaru/front
    ports:
      - "4001:4001"
  frontend:
    image: sisaru/back
    ports:
      - "5000:80"
    environment:
      - VUE_APP_API_ENDPOINT=http://backend:4001/api
